name: Prettier

# not configged yet

on:
  workflow_call:
    inputs:
      run-prettier:
        description: 'Run prettier'
        required: true
        default: 'true'

jobs:
  run-prettier:
    - name: Run prettier
      runs-on: self-hosted
      # defaults:
      #   run:
      #     working-directory: ./frontend
      steps:

        - name: Run Prettier
          run: echo 'Prettier is run here'
        # # Runs prettier
        # - name: Run code style check
        #   run: npm run prettier
